[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
favorites = "5tr3bee3syW4xAxJL9m47y4bhLScdv7v5geuzo8o6MHS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run jest --preset ts-jest"
